db/migrate/20220927142445_create_rounds.rb, db/schema.rb
Removed winner colum from Round migration file!
=> removed winner from round migration file

app/models/friendship.rb, app/models/round.rb, app/models/user.rb
Adds relations in friendship and user
=> friendship belongs to

app/models/challenge.rb, app/models/game.rb, app/models/game_round.rb, app/models/round.rb, app/models/user.rb, config/routes.rb, db/migrate/20220927143304_add_round_to_game.rb, db/migrate/20220927152330_add_reference_to_round.rb, db/migrate/20220928140435_create_game_rounds.rb, db/migrate/20220928140733_add_reference_to_game_round.rb, db/schema.rb, test/models/game_round_test.rb
=> push for testing

app/controllers/friendships_controller.rb, db/seeds.rb
Corrected a small mistake on a VERY important word, and changed one seed that was designed for Python.
=> y not ie, and one seed changed

app/channels/game_channel.rb, app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js, app/javascript/controllers/index.js, app/views/games/show.html.erb, package.json, test/channels/game_channel_test.rb, yarn.lock
Added websocket, able to connect users.
=> Added websocket, able to connect users to the server

app/controllers/friendships_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/policies/friendship_policy.rb, app/policies/user_policy.rb, app/views/friendships/index.html.erb, app/views/friendships/new.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb, yarn.lock
I'm going to try adding friends request, might have to reshape friendship or not, in doubt, better save this.
=> save before friends request try

app/controllers/games_controller.rb, app/javascript/controllers/solution_controller.js, app/views/games/show.html.erb
Output of test results is now working
=> got output of test results working

app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js, app/views/games/show.html.erb
=> we successfully got the update page

app/javascript/controllers/game_subscription_controller.js
Added readOnly functionality to codemirror
=> Clear player window on refresh

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_pages.scss, app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_sidebar.html.erb
=> New dashboard layout

app/assets/stylesheets/components/_round_winner_modal.scss, app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js, app/views/games/show.html.erb
Added game and round functionality. Next round now appears for both players via websocket. final deciding round issues a game winner modal with overall result and path to return to dashboard.
=> Added game and round functionality.

app/assets/stylesheets/pages/_game_show.scss, app/views/games/show.html.erb
=> new styling for game show

app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js, db/seeds.rb
Updated the create button to fix join game issue
=> fixed new game button so a player can join game

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_scroll_bar.scss, app/assets/stylesheets/pages/_game_show.scss, app/controllers/games_controller.rb, app/views/games/show.html.erb
No changes to ids / data-targets etc, just adding some classes
=> Styling to scroll bar and putting current user on top with green border

app/controllers/games_controller.rb
if you choose three and the other opponent chooses 5, both start new rounds.
=> fixed choosing round issue when choosing amount of rounds

app/assets/stylesheets/components/_round_choice_modal.scss, app/assets/stylesheets/components/_round_winner_modal.scss, app/javascript/controllers/game_subscription_controller.js, app/views/games/show.html.erb, app/views/pages/dashboard.html.erb
=> Modals styling

app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js
=> Changed colors for test results

app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js
Auto refresh when one player refresh has been disabled.
=> Fix refresh for both players

app/controllers/games_controller.rb, app/javascript/controllers/game_subscription_controller.js
=> Test modal

app/assets/stylesheets/pages/_game_show.scss
On my smaller screen
On my bigger screen
=> Making game show more responsive, including scroll bar for game tests

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_sidebar.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_sidebar.html.erb
=> Navbar sidebar

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/pages/dashboard.html.erb
=> Adding styling to friendslist

app/controllers/application_controller.rb, app/policies/game_policy.rb, app/views/devise/registrations/new.html.erb, app/views/pages/dashboard.html.erb, db/migrate/20220927134416_devise_create_users.rb, db/migrate/20221031190438_add_default_to_score.rb, db/schema.rb
avatar on sign up
default user score
migration file to add default score
=> Avatar on sign up

app/views/games/show.html.erb
Commented out see code button to use later.
=> removed see code button

app/assets/stylesheets/pages/_dashboard.scss, app/views/users/show.html.erb
If you are friends, the buttons says "Battle", if you are waiting for them to respond to a request, there's a message, and if you are not friends, you get add friend button
=> styling to user show

app/channels/game_channel.rb, app/javascript/controllers/game_subscription_controller.js, app/models/game.rb
Fixed issue with users being able to join a game that noone has played.
ie: Nicola can't keep stealing points....
=> game is now destroyed if you exit a game and player_two is still ID 1

app/assets/stylesheets/components/_invite_modal.scss, app/assets/stylesheets/components/_pre_game_modal.scss, app/assets/stylesheets/pages/_dashboard.scss, app/controllers/games_controller.rb, app/controllers/pages_controller.rb, app/javascript/controllers/friend_controller.js, app/javascript/controllers/ninjaform_controller.js, app/views/pages/dashboard.html.erb, app/views/shared/_pre_game_modal.html.erb, app/views/users/show.html.erb, config/routes.rb
most of inviting friends front end working, typed js still broken
=> most of inviting friends front end working, typed js still broken

app/javascript/controllers/friend_controller.js, app/views/pages/dashboard.html.erb, app/views/shared/_pre_game_modal.html.erb
Changed name of function from checked to updateGameForm,
Fixed issue with typed.js added new Typed everytime.
=> Typedjs issue

app/controllers/games_controller.rb
=> refactored user_code user_ready_next_round

app/controllers/games_controller.rb, app/models/league.rb, app/models/user.rb, db/migrate/20221127191854_create_leagues.rb, db/migrate/20221130083251_add_column_to_users.rb, db/migrate/20221130084226_add_league_to_games.rb, db/schema.rb, test/models/game_test.rb, test/models/league_test.rb, test/models/user_test.rb
Added league table
Added references to users and games (league.users | league.games)
Added tests to leagues and games to make sure a game can be saved without a league, and a league has many users and games.
=> Create league table

app/controllers/games_controller.rb, app/models/game.rb
moved game_test method into the game model to keep controller tidy
=> Move game test

config/cable.yml
testing a redis config to see if it works
=> trying to configure redis

app/controllers/application_controller.rb, app/controllers/games_controller.rb, app/models/game.rb, app/models/game_round.rb, app/views/games/show.html.erb
=> Revert "Refactor game show"

Gemfile, Gemfile.lock, app/channels/game_channel.rb, app/controllers/games_controller.rb, app/javascript/controllers/code_controller.js, app/javascript/controllers/game_subscription_controller.js, app/javascript/utils/fileUtils.js, app/views/games/show.html.erb, config/environments/development.rb
Updated code to not make a database queries each time we type
Added file utils for post and patch to be used over multiple controllers 
Changed game channel to reduce database queries
changed forfeit button to call an action in the stimulus controller
=> Updated the code to reduce amount of database queries

app/assets/stylesheets/application.scss, app/javascript/controllers/code_controller.js, app/views/shared/_player_solutions_modal.html.erb
refactored code controller to make it more maintainable
=> Refactored code controller

app/channels/friend_channel.rb, app/controllers/application_controller.rb, app/controllers/games_controller.rb, app/javascript/controllers/friend_controller.js, app/models/user.rb, app/views/pages/_friends.html.erb, app/views/pages/_latest_battles_table.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, db/migrate/20231113163412_add_online_to_users.rb, db/schema.rb
**Now when a user is logged in and on the dashboard the battle button turns green without the need to refresh**
Updated the friend channel for subscribed and unsubscribed
Updated buttons to handle change in player online status
fixed button to when sending friend request
=> Added real time battle button updates

Gemfile, Gemfile.lock, spec/models/game_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb
=> Write user test
